name: generate-pacman-game-from-github-contribution-grid
on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:
permissions:
  contents: write 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: abozanona/pacman-contribution-graph@1.0.10.2
        with:
          github_user_name: Alyyyy88
          github_token: ${{ secrets.GITHUB_TOKEN }}
