name: generate-pacman-game-from-github-contribution-grid
on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: abozanona/pacman-contribution-graph@1.0.10.2
        with:
          username: ${{ github.repository_owner }}
          output_file: output/pacman-contribution-graph.svg
